GET http://localhost:5283/Estate
Cookie: .AspNetCore.Identity.Application=CfDJ8MNQ5GkX9XNGnuLl7MppiHJBFXnYND2XSQcCO4KMRe1NMwxWcUx52PSRLh9EnZEegBacs2F5BlWQ8xccYL1c_PUVVPqEd7kzD8ihvwpDDEQNrUPoO3RgUTWTFlHe8rb-M_N3rAROx95e_ASaKrCFAk-_HUlvjDxu-tik0g_710xtyhoT0BO4xlkaeaZ79LF8EkEw_9jQZFHFW_wUIy5j2ebF8_FXfFcfxgu-Qjd98Yn58KOtLtlyVL33w9POUEKj8Jc1CV7mzdf7EUXGPtxxcAy56_0RzaxWaJCZtVU0DwFJzTvTWhqdtvpAwGuKQryY_Wn1GHoRS-oo9o1rwRcetzqJGND4nOc8Vs4tuBCbQR1ubnDqpHStsyljW0bQBz5sF9gbz91s0aXtSLynf6Rn3HNZjabmT3maTFnAAB7QQa1CBlUhvooI7itmvtojeVyDLL7D4NuKt_c-6RmFE1lpJ1kCuAv0BXQ-RQx7BLyd7cSLaFxjb4LLB43n8ijPQ96_qwdy8X4a5FzQFbLiTQDiBGMubnabvlEobmi_ZBm_WFwCjOXpHA9KVYTGF282UTADpmMTWUcz9xKGspC5iYJqoExdBaNLTMYm39SRKxV3kPzLr7_YQ7hBvzQZWdntqg9MnCtWhYIb_AVolHtvyIvOjDnbFaQ-1IkOhSig_QYG84QjAIV-mcJxRGNsk_m7JPmqQEHJKSEFKDvajqI2M9C6Tju57DaARF8Oafhh_9iFWK5B
Content-Type: application/json
Body:
{

}